name: Docker Image CI

on:
  push:
    branches: [ dev_mari ]
  pull_request:
    branches: [ dev_mari ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/hexapayloaddecoder:latest
    - name: Docker Push
      run: |
        docker push ${{secrets.DOCKER_USER}}/hexapayloaddecoder:latest
    - name: Webhook to Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: always() # Pick up events even if the job fails or is canceled.
